### ISSUE TITLE
2.3.7版本视频闪退

### ISSUE THREAD

**Issue by Runzelee** [670848654/SakuraAnime#40]
最新2.3.7版本，历史记录点进视频继续播放时，视频播放到一半突然闪退，每次需要清除数据才能解决问题。
之前版本好像有类似issue
日志：
```
time: 1660476158887
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'com.alibaba.fastjson.JSONArray com.alibaba.fastjson.JSONObject.getJSONArray(java.lang.String)' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'com.alibaba.fastjson.JSONArray com.alibaba.fastjson.JSONObject.getJSONArray(java.lang.String)' on a null object reference
	at my.project.sakuraproject.main.player.PlayerActivity.V0(PlayerActivity.java:3)
	at my.project.sakuraproject.main.player.PlayerActivity.W0(Unknown Source:0)
	at my.project.sakuraproject.main.player.i0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by 670848654** [comment]
什么番？我看看，JSON相关的错误应该是弹幕处理出现的问题，你先试试在设置里关闭弹幕功能看能正常播放不。

**Comment by Runzelee** [comment]
MaliMali源Lycoris Recoil第七集，今天突然又好了，问题暂时不能重现，昨天可能是网络问题吧😂
估计是弹幕api错误处理上不是很妥
