### ISSUE TITLE
2.5.9版本闪退问题严重

### ISSUE THREAD

**Issue by lovecomic** [670848654/SakuraAnime#70]
机型：红米K30PRO MIUI4.0.4 安卓12
步骤：Yhdm源-新番时间表-周六-破灭之国、不死不幸等等
一点就闪退到首页，无法点进动漫详情页。。

![815095aba7b5cc42b06291c5a8f3b44](https://github.com/670848654/SakuraAnime/assets/25029053/eca5f98c-3098-4b6f-9635-e819d710dbd1)
![ae9d051b29113d8771f67cc6e144ce7](https://github.com/670848654/SakuraAnime/assets/25029053/2265b298-2a8d-4098-bb55-945734520773)

**Comment by lovecomic** [comment]
闪退问题：
java.lang.IllegalArgumentException: Must not be null or empty
	at b3.j.b(Preconditions.java:2)
	at n2.g.<init>(GlideUrl.java:9)
	at n2.g.<init>(GlideUrl.java:2)
	at l8.h.K(Utils.java:2)
	at my.project.sakuraproject.adapter.AnimeDescMultiRecommendAdapter.a(AnimeDescMultiRecommendAdapter.java:5)
	at my.project.sakuraproject.adapter.AnimeDescMultiRecommendAdapter.convert(Unknown Source:2)
	at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:7)
	at com.chad.library.adapter.base.BaseQuickAdapter.onBindViewHolder(BaseQuickAdapter.java:1)
	at androidx.recyclerview.widget.RecyclerView$g.onBindViewHolder(Unknown Source:0)
	at androidx.recyclerview.widget.RecyclerView$g.bindViewHolder(RecyclerView.java:6)
	at androidx.recyclerview.widget.RecyclerView$u.H(RecyclerView.java:6)
	at androidx.recyclerview.widget.RecyclerView$u.I(RecyclerView.java:47)
	at androidx.recyclerview.widget.RecyclerView$u.p(Unknown Source:5)
	at androidx.recyclerview.widget.RecyclerView$u.o(Unknown Source:1)
	at androidx.recyclerview.widget.LinearLayoutManager$c.d(LinearLayoutManager.java:3)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:64)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:8)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:12)
	at android.view.View.measure(View.java:26212)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26212)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26212)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:5)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:1)
	at android.view.View.measure(View.java:26212)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:9)
	at android.view.View.measure(View.java:26212)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.N(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:35)
	at android.view.View.measure(View.java:26212)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
	at android.view.View.measure(View.java:26212)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26212)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26212)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26212)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7020)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:832)
	at android.view.View.measure(View.java:26212)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3788)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2562)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2841)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2277)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9037)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
	at android.view.Choreographer.doCallbacks(Choreographer.java:946)
	at android.view.Choreographer.doFrame(Choreographer.java:875)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by 670848654** [comment]
新版本已修复
